baseURL = "https://bargavkondapu.com"
languageCode = "en-us"
title = "Bargav Kondapu"

[params]
  description = "Hi. I am Bargav Kondapu"
  author = "Bargav Kondapu"
  author_description = "Bargav Kondapu is a web application developer"
  author_image="/images/bk-profile-sm.jpeg"
  copyright = "© 2018 Bargav Kondapu "


  [[menu.main]]
    name = "Notes"
    url = "/notes"
    weight = 100

  [[menu.main]]
    name = "Interactions"
    url = "/interactions"
    weight = 99

  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 98

  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 97
